--- 
abstract: InputMonster sources for common Catalyst sources
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 0.005
license: perl
name: Data-InputMonster-Util-Catalyst
requires: 
  Carp: 0
  Data::InputMonster: 0.005
  Sub::Exporter: 0
version: 0.002
